### ISSUE TITLE
glibc version conflict error

### ISSUE THREAD

**Issue by johnwason** [conda-forge/dotnet-feedstock#32]
- [x ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

I am getting a strange glibc conflict error when building using conda-smithy on GitHub Actions. The build works locally, so I am not sure why it is happening.

```
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/conda_build/environ.py", line 802, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/opt/conda/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/opt/conda/lib/python3.8/site-packages/conda/plan.py", line 474, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/opt/conda/lib/python3.8/site-packages/conda/core/solve.py", line 114, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
  File "/opt/conda/lib/python3.8/site-packages/conda/core/solve.py", line 157, in solve_for_diff
    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
  File "/opt/conda/lib/python3.8/site-packages/conda/core/solve.py", line 281, in solve_final_state
    ssc = self._run_sat(ssc)
  File "/opt/conda/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/opt/conda/lib/python3.8/site-packages/conda/core/solve.py", line 815, in _run_sat
    ssc.solution_precs = ssc.r.solve(tuple(final_environment_specs),
  File "/opt/conda/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/opt/conda/lib/python3.8/site-packages/conda/resolve.py", line 1322, in solve
    self.find_conflicts(specs, specs_to_add, history_specs)
  File "/opt/conda/lib/python3.8/site-packages/conda/resolve.py", line 348, in find_conflicts
    bad_deps = self.build_conflict_map(specs, specs_to_add, history_specs)
  File "/opt/conda/lib/python3.8/site-packages/conda/resolve.py", line 456, in build_conflict_map
    self._get_package_pool((spec, ))
  File "/opt/conda/lib/python3.8/site-packages/conda/resolve.py", line 555, in _get_package_pool
    pool = self.get_reduced_index(specs)
  File "/opt/conda/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/opt/conda/lib/python3.8/site-packages/conda/resolve.py", line 576, in get_reduced_index
    explicit_specs, features = self.verify_specs(explicit_specs)
  File "/opt/conda/lib/python3.8/site-packages/conda/resolve.py", line 288, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound: 
  - __glibc[version='>=2.17,>=2.17,<3.0.a0']
```

Here is the action log:

https://github.com/robotraconteur-conda/gazebo_model_robotraconteur_driver-feedstock/runs/2660650406?check_suite_focus=true

**Comment by acesnik** [comment]
This happens for me when building targeting CentOS 6, which is still the default I think. You could try explicitly targeting CentOS 7 and see if that fixes it. Like done here: https://www.github.com/conda-forge/dotnet-feedstock/tree/master/conda-forge.yml

**Comment by acesnik** [comment]
https://conda-forge.org/docs/maintainer/knowledge_base.html#using-centos-7

**Comment by johnwason** [comment]
Thanks, that fixed it.
